/*
  C-file generated by µC/GUI-FontConvert Demo  V2.16b
  Compiled:    Jul 23 2002 at 13:13:49

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  






http://www.ucgui.com
2005/07/24
www.ucgui.com


  Source file: SongTi18_Warning.c
  Font:        __
  Height:      24
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontSongTi18_Warning;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_FLASH const unsigned char acFontSongTi18_Warning_4EBA[ 72] = { /* code 4EBA */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,__X__X__,________,
  ________,__X__X__,________,
  ________,_XX__X__,________,
  ________,_XX___X_,________,
  ________,_X____X_,________,
  ________,XX____XX,________,
  ________,X______X,X_______,
  _______X,X_______,X_______,
  ______XX,________,XX______,
  _____XX_,________,_XXX____,
  ____XX__,________,__XXXX__,
  ___X____,________,___XXX__,
  __X_____,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_4F4D[ 72] = { /* code 4F4D */
  ________,________,________,
  ______X_,________,________,
  ______XX,_____X__,________,
  ______X_,_____XX_,________,
  ______X_,______X_,________,
  _____XX_,______X_,________,
  _____X__,________,___XX___,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,________,________,
  ____XX__,________,__XX____,
  ___X_X__,__X_____,_XX_____,
  __X__X__,__X_____,_XX_____,
  __X__X__,___X____,_X______,
  _X___X__,___X____,_X______,
  _____X__,___XX___,_X______,
  _____X__,___XX___,XX______,
  _____X__,___XX___,X_______,
  _____X__,____X___,X_______,
  _____X__,________,X_______,
  _____X__,_______X,________,
  _____X__,_______X,____XX__,
  _____X_X,XXXXXXXX,XXXXXXX_,
  _____X__,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_5165[ 72] = { /* code 5165 */
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  ________,XX______,________,
  ________,__XX____,________,
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XX_X__,________,
  ________,__X__X__,________,
  ________,_XX__X__,________,
  ________,_XX___X_,________,
  ________,_X____XX,________,
  ________,X_____XX,________,
  _______X,X______X,X_______,
  _______X,________,XX______,
  ______X_,________,XXX_____,
  _____X__,________,_XXX____,
  ____X___,________,__XXX___,
  ___X____,________,___XXXX_,
  __X_____,________,____X___,
  _X______,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_52E4[ 72] = { /* code 52E4 */
  ________,________,________,
  ____X___,_X______,________,
  ____XX__,_XX_____,XX______,
  ____XX__,_X__X___,X_______,
  _XXXXXXX,XXXXXX__,X_______,
  ____XX__,_X______,X_______,
  ____XX__,_X______,X_______,
  ____XXXX,XX______,X____X__,
  _______X,_____XXX,XXXXXX__,
  ___XXXXX,XXXXX___,X____X__,
  ___X___X,___X____,X____X__,
  ___X___X,___X____,X____X__,
  ___X___X,___X____,X____X__,
  ___XXXXX,XXXX____,X____X__,
  _______X,___X____,X____X__,
  ___XXXXX,XXXXX__X,X___XX__,
  _______X,_______X,____XX__,
  _______X,___X___X,____XX__,
  ____XXXX,XXX___X_,____XX__,
  _______X,______X_,____X___,
  _______X,XXXXXX__,X___X___,
  _XXXXXX_,____X___,_XXXX___,
  __X_____,___X____,__XX____,
  ________,__X_____,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_5355[ 72] = { /* code 5355 */
  ________,________,________,
  ________,_______X,________,
  _______X,X______X,X_______,
  ________,XX_____X,________,
  ________,_X____X_,________,
  ________,_X___X__,________,
  _____XXX,XXXXXXXX,XXXX____,
  _____X__,___X____,__X_____,
  _____X__,___X____,__X_____,
  _____X__,___X____,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,___X____,__X_____,
  _____X__,___X____,__X_____,
  _____X__,___X____,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  ________,___X____,________,
  ________,___X____,____XX__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_53F7[ 72] = { /* code 53F7 */
  ________,________,________,
  ________,________,________,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,________,
  ________,________,____XX__,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,_XX_____,
  _______X,_XXXXXXX,XXX_____,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,XX______,
  ________,________,XX______,
  ________,___XXXXX,X_______,
  ________,_____XXX,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_540D[ 72] = { /* code 540D */
  ________,________,________,
  ________,________,________,
  ________,__X_____,________,
  ________,_XX_____,________,
  ________,_X______,__X_____,
  ________,XXXXXXXX,XXXX____,
  _______X,X_______,_XX_____,
  _______X,________,XX______,
  ______X_,X______X,X_______,
  _____X__,_XX___XX,________,
  ____X___,_XX__XX_,________,
  ___X____,____XX__,________,
  ________,___XX___,________,
  ________,__XX____,________,
  ________,XX______,___XX___,
  _______X,X_XXXXXX,XXXX____,
  _____XX_,X_______,___X____,
  ___XX___,X_______,___X____,
  __X_____,X_______,___X____,
  ________,X_______,___X____,
  ________,X_______,___X____,
  ________,XXXXXXXX,XXXX____,
  ________,X_______,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_5730[ 72] = { /* code 5730 */
  ________,________,________,
  ________,________,________,
  ____X___,______XX,X_______,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,__XX___X,________,
  ____XX__,__XX___X,________,
  ____XX__,__XX___X,___XX___,
  ____XX__,__XX___X,XXXX____,
  ____XX_X,X_XX__XX,___X____,
  __XXXXX_,__XXXX_X,___X____,
  ____XX__,XXXX___X,___X____,
  ____XX__,__XX___X,___X____,
  ____XX__,__XX___X,___X____,
  ____XX__,__XX___X,___X____,
  ____XX__,__XX__XX,XXXX____,
  ____XX__,__XX__XX,__XX_X__,
  ____XX__,XXXX__XX,_____X__,
  ____XXXX,__XX__X_,_____X__,
  __XXX___,__XX____,_____X__,
  _XX_____,__XX____,_____XX_,
  ________,___XXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_59D3[ 72] = { /* code 59D3 */
  ________,________,________,
  ________,________,________,
  _____XX_,________,XX______,
  _____X__,________,X_______,
  _____X__,________,X_______,
  ____XX__,____XX__,X_______,
  ____XX__,___XX___,X_______,
  _XXXXXXX,XX_XX___,X___X___,
  ____X___,XX_XXXXX,XXXXXX__,
  ____X___,X__X____,X_______,
  ___XX___,X__X____,X_______,
  ___X____,X_X_____,X_______,
  ___X___X,X_X_____,X_______,
  ___X___X,_X______,X___X___,
  __XX___X,___XXXXX,XXXXXX__,
  __XX___X,________,X_______,
  ____XXXX,________,X_______,
  ______XX,X_______,X_______,
  _____XX_,XX______,X_______,
  _____X__,_X______,X_______,
  ____X___,________,X____X__,
  ___X____,__XXXXXX,XXXXXXX_,
  __X_____,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_5C5E[ 72] = { /* code 5C5E */
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XX__,________,___X____,
  ____XX__,________,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,________,___X____,
  ____XX__,________,XXXX____,
  ____XX_X,XXXXXXXX,X_______,
  ____XX__,_____XX_,________,
  ____XX__,X____XX_,___X____,
  ____XX__,XXXXXXXX,XXXX____,
  ____XX__,XX___XX_,__XX____,
  ____XX__,XXXXXXXX,XXXX____,
  ____X___,X____XX_,__X_____,
  ____X__X,_____XX_,____X___,
  ____X__X,XXXXXXXX,XXXXX___,
  ____X__X,_____XX_,X___X___,
  ___X___X,_____XX_,XXX_X___,
  ___X___X,__XXX__X,__X_X___,
  __X____X,________,_X__X___,
  __X____X,________,_XXXX___,
  _X_____X,________,___XX___,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_6240[ 72] = { /* code 6240 */
  ________,________,________,
  ________,________,________,
  ________,_XX_____,___XXX__,
  _______X,XX______,XXXX____,
  ____XXX_,_____XXX,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____XXXX,XXX__X__,_____X__,
  ____X___,_XX__XXX,XXXXXXX_,
  ____X___,_XX__X__,__X_____,
  ____X___,_XX__X__,__X_____,
  ____X___,_XX__X__,__X_____,
  ____X___,_XX__X__,__X_____,
  ____XXXX,XXX_XX__,__X_____,
  ____X___,_X__XX__,__X_____,
  ___XX___,____X___,__X_____,
  ___XX___,___XX___,__X_____,
  ___X____,___X____,__X_____,
  ___X____,__XX____,__X_____,
  __X_____,__X_____,__X_____,
  __X_____,_X______,__X_____,
  _X______,X_______,__X_____,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_6267[ 72] = { /* code 6267 */
  ________,________,________,
  _____X__,________,________,
  _____XXX,_____XX_,________,
  _____XX_,_____X__,________,
  ______X_,_____X__,________,
  ______X_,_____X__,________,
  ______X_,_X___X__,________,
  _XXXXXXX,XXX__X__,_XX_____,
  ______X_,_XXXXXXX,XXX_____,
  ______X_,_____X__,_XX_____,
  ______X_,_____X__,_XX_____,
  ______X_,XX___X__,_X______,
  _____XXX,_____X__,_X______,
  __XXX_X_,___XXX__,_X______,
  _XX___X_,____XX__,_XX_____,
  ______X_,____X_XX,_XX_____,
  ______X_,____X__X,XXX___X_,
  ______X_,___X____,__X__X__,
  ______X_,___X____,__X__X__,
  ______X_,__X_____,__XX_X__,
  _____XX_,_X______,___XXX__,
  ___XXXX_,X_______,____XX__,
  ____XX_X,________,_____XX_,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_6C11[ 72] = { /* code 6C11 */
  ________,________,________,
  ________,________,________,
  ________,________,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,________,_XX_____,
  ____X___,________,_XX_____,
  ____X___,________,_XX_____,
  ____X___,________,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ____X___,___XX___,____X___,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____XX__,________,
  ____X___,_____X__,________,
  ____X___,_____XX_,_____X__,
  ____X___,_XX___XX,_____X__,
  ____X__X,X______X,X____X__,
  ____XXX_,________,XX__XX__,
  ___XXX__,________,_XXXXX__,
  ____X___,________,___XXX__,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_6CD5[ 72] = { /* code 6CD5 */
  ________,________,________,
  ________,______X_,________,
  ___X____,______XX,________,
  ____XX__,______X_,________,
  _____X__,______X_,________,
  _____X__,X_____X_,________,
  ________,X_____X_,___XX___,
  _______X,_XXXXXXX,XXX_____,
  _XX____X,______X_,________,
  __XX__X_,______X_,________,
  ___X__X_,______X_,________,
  ___X__X_,______X_,_____X__,
  _____X_X,XXXXXXXX,XXXXXXX_,
  _____X__,______X_,________,
  _____X__,_____XX_,________,
  ____X___,_____X__,________,
  _XXXX___,____X___,________,
  ___XX___,___XX___,_XX_____,
  ___XX___,___X____,___X____,
  ___XX___,__X_____,___XX___,
  ___XX___,XXXXXXXX,XXX_XX__,
  ___XX___,XXXX____,____XX__,
  ________,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_6D4B[ 72] = { /* code 6D4B */
  ________,________,________,
  ________,________,________,
  ___X___X,________,____XX__,
  ____X__X,XXXXXXX_,____X___,
  ____XX_X,X____XX_,____X___,
  _____X_X,X____XX_,_X__X___,
  _______X,X_X__XX_,_X__X___,
  _X_____X,X_XX_XX_,_X__X___,
  __XX__XX,X_XX_XX_,_X__X___,
  ___X__XX,X_XX_XX_,_X__X___,
  ___X_X_X,X_XX_XX_,_X__X___,
  _____X_X,X_XX_XX_,_X__X___,
  _____X_X,X_XX_XX_,_X__X___,
  _____X_X,X_XX_XX_,_X__X___,
  ____X__X,X_X__XX_,_X__X___,
  ____X__X,X_X__XX_,_X__X___,
  __XXX__X,X_X__X__,_X__X___,
  ___XX___,__X_____,_X__X___,
  ___XX___,_X_XX___,____X___,
  ___XX___,_X___X__,____X___,
  ___XX___,X____XX_,____X___,
  ___XX__X,______X_,__XXX___,
  _____XX_,________,___XX___,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_70B9[ 72] = { /* code 70B9 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___X____,________,
  ________,___X____,___X____,
  ________,___XXXXX,XXXXX___,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ______X_,___X____,_XX_____,
  ______XX,XXX_XXXX,XXX_____,
  ______X_,________,_XX_____,
  ______X_,________,_XX_____,
  ______X_,________,_XX_____,
  ______X_,________,_XX_____,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_XX_____,
  ________,________,________,
  ________,X____X__,__X_____,
  ____X___,_X____X_,___XX___,
  ____X___,_XX___XX,____X___,
  ___XX___,__X____X,____XX__,
  __XX____,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_724C[ 72] = { /* code 724C */
  ________,________,________,
  ________,________,________,
  ______XX,_______X,________,
  ___X__XX,______X_,________,
  ___X__XX,___XXXXX,XXXXX___,
  ___X__XX,___X___X,X___X___,
  ___X__XX,___X___X,X___X___,
  ___X__XX,___X___X,X___X___,
  ___X__XX,XX_XXXXX,XXXXX___,
  ___XXX__,___X___X,____X___,
  ___X____,___X___X,____X___,
  ___X____,___X___X,____X___,
  ___X____,___XXXXX,XXXXX___,
  ___XXXXX,X__X__XX,____X___,
  ___X___X,_____X__,XX______,
  ___X___X,____X___,X_______,
  ___X___X,__XX____,X____X__,
  ___X___X,_XXXXXXX,XXXXXXX_,
  __XX___X,________,X_______,
  __X____X,________,X_______,
  __X____X,________,X_______,
  _X_____X,________,X_______,
  _X_____X,________,X_______,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_7801[ 72] = { /* code 7801 */
  ________,________,________,
  ________,________,________,
  ________,________,___X____,
  _XXXXXXX,XX_XXXXX,XXXXX___,
  _____X__,__X_____,___X____,
  ____XX__,____XX__,___X____,
  ____X___,____XX__,___X____,
  ____X___,____X___,__XX____,
  ____X___,____X___,__XX____,
  ___X___X,X___X___,__X_____,
  ___XXXXX,X___X___,__X_____,
  __XXX__X,X___X___,__X_____,
  __XXX__X,X__XXXXX,XXXXXX__,
  _X_XX__X,X_______,_____X__,
  ___XX__X,X_______,_____X__,
  ___XX__X,X_______,_____X__,
  ___XX__X,XXXXXXXX,XXX_XX__,
  ___XX__X,X_______,___XXX__,
  ___XXXXX,X_______,____X___,
  ___XX__X,X_______,____X___,
  ___XX___,_______X,X___X___,
  ___X____,________,_XXXX___,
  ________,________,__XX____,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_88AB[ 72] = { /* code 88AB */
  ________,________,________,
  ________,________,________,
  ____XX__,_______X,X_______,
  _____XX_,_______X,________,
  _____X__,_______X,________,
  ________,__X____X,________,
  __XXXXXX,X_XXXXXX,XXXXXX__,
  _______X,__XX___X,____X___,
  ______X_,__XX___X,___X____,
  ______X_,__XX___X,________,
  _____X__,X_XX___X,________,
  ____XX__,XXXX___X,___X____,
  ____XX_X,__XXXXX_,XXXXX___,
  ___X_XX_,__XX_X__,__XX____,
  __X__X_X,__XX_X__,__XX____,
  _X___X__,X_X___X_,__X_____,
  _____X__,X_X___X_,_X______,
  _____X__,__X____X,XX______,
  _____X__,__X____X,X_______,
  _____X__,_X____XX,XX______,
  _____X__,_X___XX_,_XXX____,
  _____X__,X___X___,___XXXX_,
  _____X_X,__XX____,____XX__,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8B66[ 72] = { /* code 8B66 */
  ________,________,________,
  _____X__,________,________,
  _____XX_,_X_____X,X_______,
  _____XX_,_X__X__X,________,
  __XXXXXX,XXXX_XXX,XXXXXX__,
  ____XX__,___X__XX,__XX____,
  ___XXXXX,XXXXXX_X,__X_____,
  ___XX___,X__X_X_X,__X_____,
  __X_XXXX,X__X____,XX______,
  ____XXXX,X__X____,XX______,
  ____X__X,__X____X,__XX____,
  ________,XXX___X_,___XXX__,
  ________,_X_XXX__,________,
  ________,____X___,___XX___,
  ___XXXXX,XXXX_XXX,XXX_____,
  _____XXX,XXXXXXXX,XX______,
  ________,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ________,________,X_______,
  _____XXX,XXXXXXXX,XX______,
  _____XX_,________,XX______,
  _____XXX,XXXXXXXX,XX______,
  _____XX_,________,XX______,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8BC1[ 72] = { /* code 8BC1 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,____XX__,
  ____XX__,_XXXXXXX,XXXXXXX_,
  _____X__,_______X,________,
  _____X__,_______X,________,
  ________,_______X,________,
  ________,_______X,________,
  ____X___,__X____X,________,
  _XXXXX__,__XX___X,________,
  ____XX__,__X____X,___XX___,
  ____XX__,__X____X,XXXXXX__,
  ____XX__,__X____X,________,
  ____XX__,__X____X,________,
  ____XX__,__X____X,________,
  ____XX__,X_X____X,________,
  ____XX_X,__X____X,________,
  ____XXX_,__X____X,________,
  ____XXX_,__X____X,________,
  ____XX__,__X____X,_____X__,
  _______X,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8BD5[ 72] = { /* code 8BD5 */
  ________,________,________,
  ________,________,________,
  ________,_______X,X_X_____,
  ___X____,_______X,XX_XX___,
  ____X___,________,X___X___,
  ____XX__,________,X___X___,
  _____X__,________,X____X__,
  ________,XXXXXXXX,XXXXXXX_,
  ________,________,X_______,
  ________,________,X_______,
  _____X__,________,X_______,
  __XXXX__,______X_,X_______,
  _____X__,_XXXXX_X,XX______,
  _____X__,____X___,XX______,
  _____X__,____X___,_X______,
  _____X__,____X___,_X______,
  _____X__,_X__X___,_XX_____,
  _____X__,X___X___,__X___X_,
  _____X_X,____XXXX,__XX_X__,
  _____XXX,__XXX___,___X_X__,
  _____XX_,XXX_____,___XXX__,
  _____X__,________,____XXX_,
  ________,________,_____XX_,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8BF7[ 72] = { /* code 8BF7 */
  ________,________,________,
  ________,______X_,________,
  ___X____,______XX,________,
  ____X___,______XX,____X___,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____XX__,______XX,________,
  ________,______XX,___X____,
  ________,__XXXXXX,XXXXX___,
  ________,______XX,________,
  _XXXXX__,______XX,____XX__,
  ____XX__,XXXXXXXX,XXXXXXX_,
  ____XX__,________,________,
  ____XX__,__XXXXXX,XXXX____,
  ____XX__,__XX____,___X____,
  ____XX__,__XX____,___X____,
  ____XX__,__XXXXXX,XXXX____,
  ____XX__,X_XX____,___X____,
  ____XX_X,__XX____,___X____,
  ____XXX_,__XXXXXX,XXXX____,
  ____XXX_,__XX____,___X____,
  ____XX__,__XX____,___X____,
  ________,__XX___X,XXXX____,
  ________,__XX____,__X_____,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8F66[ 72] = { /* code 8F66 */
  ________,________,________,
  ________,________,________,
  ________,_XXX____,________,
  ________,_XX_____,________,
  ________,_X______,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,X_______,________,
  _______X,X__XX___,________,
  _______X,___XX___,________,
  ______XX,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,__X_____,
  ____XX_X,XXXXXXXX,XX______,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,____XX__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_8F93[ 72] = { /* code 8F93 */
  ________,________,________,
  ________,________,________,
  _____XX_,______XX,________,
  ____XX__,______XX,________,
  ____X___,_____XX_,X_______,
  ____X___,XX__XX__,_X______,
  __XXXXXX,____X___,__X_____,
  ___X____,___X____,_XXXX___,
  ___X_XX_,__XXXXXX,XXX_XXX_,
  __XX__X_,_X______,____X___,
  __X___X_,_X____X_,____X___,
  _XX___XX,X_XXXXX_,_X__X___,
  ___XXXX_,__X___X_,_X__X___,
  ______X_,__X___X_,_X__X___,
  ______X_,__XXXXX_,_X__X___,
  ______X_,__X___X_,_X__X___,
  ____XXXX,__X___X_,_X__X___,
  _XXX__X_,__XXXXX_,_X__X___,
  ______X_,__X___X_,_X__X___,
  ______X_,__X___X_,____X___,
  _____XX_,__X___X_,____X___,
  _____XX_,__X___X_,_XXXX___,
  _____XX_,__X__XX_,___XX___,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_90E8[ 72] = { /* code 90E8 */
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  _______X,X______X,_____X__,
  ________,X___X__X,XXXXXXX_,
  __XXXXXX,XXXXXX_X,____XX__,
  ________,__X____X,____X___,
  ____X___,__XX___X,____X___,
  _____X__,__X____X,___X____,
  _____XX_,_XX____X,___X____,
  _____X__,_X___X_X,__X_____,
  _XXXXXXX,XXXXXXXX,__X_____,
  ________,_______X,___X____,
  ________,___X___X,____X___,
  ____XXXX,XXXXX__X,____XX__,
  ____X___,___X___X,_____X__,
  ____X___,___X___X,_____X__,
  ____X___,___X___X,_____X__,
  ____X___,___X___X,_XXXXX__,
  ____X___,___X___X,___XX___,
  ____XXXX,XXXX___X,________,
  ____X___,___X___X,________,
  ________,_______X,________,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_95E8[ 72] = { /* code 95E8 */
  ________,________,________,
  ________,________,________,
  ______X_,________,________,
  _______X,X_______,___X____,
  _______X,X__XXXXX,XXXXX___,
  _______X,X_______,___XX___,
  ____XX__,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,________,___XX___,
  ____X___,_______X,X__XX___,
  ____X___,________,_XXX____,
  ____X___,________,__X_____,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_9A76[ 72] = { /* code 9A76 */
  ________,________,________,
  ________,________,________,
  ________,________,X_______,
  ________,X_______,X_______,
  __XXXXXX,X_______,X_______,
  ________,X_______,X_______,
  ____XX__,X__XXXXX,XXXXXX__,
  ____X___,X__XX___,X___X___,
  ____X___,X__XX___,X___X___,
  ___XX__X,X__XX___,X___X___,
  ___X___X,X__XX___,X___X___,
  ___X___X,___XX___,X___X___,
  ___X___X,_X_XXXXX,XXXXXX__,
  ___XXXXX,XXXXX___,X___XX__,
  ________,_X__X___,X_______,
  ________,_X___X__,X_______,
  _____XXX,XX___X__,X_______,
  _XXXX___,XX____XX,X_______,
  __X_____,X______X,________,
  ________,X_____XX,X_______,
  ____X___,X____X__,_XX_____,
  _____XXX,X__XX___,__XXXXX_,
  ______XX,XXX_____,____XX__,
  ________,________,________};

GUI_FLASH const unsigned char acFontSongTi18_Warning_9A7E[ 72] = { /* code 9A7E */
  ________,________,________,
  ______X_,________,________,
  ______XX,________,________,
  ______XX,___X__XX,XXXXX___,
  ___XXXXX,XXXX__X_,____X___,
  ______X_,___X__X_,____X___,
  ______X_,___X__X_,____X___,
  _____XX_,__XX__X_,____X___,
  _____X_X,XXXX__XX,XXXXX___,
  ____X___,_XX___X_,________,
  ___X____,________,________,
  __X__XXX,XXXXXXXX,XX______,
  ________,X_______,X_______,
  _______X,X_______,X_______,
  _______X,________,X___X___,
  ______XX,XXXXXXXX,XXXXXX__,
  _______X,________,____X___,
  ________,________,____X___,
  ________,________,XX_XX___,
  ___XXXXX,XXXXXXXX,___XX___,
  ________,________,___XX___,
  ________,_______X,XXXX____,
  ________,________,_XXX____,
  ________,________,________};

/* Start of unicode area <Halfwidth and Fullwidth Forms> */
GUI_FLASH const unsigned char acFontSongTi18_Warning_FF01[ 72] = { /* code FF01 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,________,________,
  ______XX,________,________,
  ______XX,________,________,
  ______XX,________,________,
  _______X,________,________,
  _______X,________,________,
  _______X,________,________,
  _______X,________,________,
  ________,________,________,
  ________,________,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_FLASH const GUI_CHARINFO GUI_FontSongTi18_Warning_CharInfo[30] = {
   {  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_4EBA } /* code 4EBA */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_4F4D } /* code 4F4D */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_5165 } /* code 5165 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_52E4 } /* code 52E4 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_5355 } /* code 5355 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_53F7 } /* code 53F7 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_540D } /* code 540D */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_5730 } /* code 5730 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_59D3 } /* code 59D3 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_5C5E } /* code 5C5E */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_6240 } /* code 6240 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_6267 } /* code 6267 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_6C11 } /* code 6C11 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_6CD5 } /* code 6CD5 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_6D4B } /* code 6D4B */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_70B9 } /* code 70B9 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_724C } /* code 724C */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_7801 } /* code 7801 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_88AB } /* code 88AB */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8B66 } /* code 8B66 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8BC1 } /* code 8BC1 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8BD5 } /* code 8BD5 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8BF7 } /* code 8BF7 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8F66 } /* code 8F66 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_8F93 } /* code 8F93 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_90E8 } /* code 90E8 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_95E8 } /* code 95E8 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_9A76 } /* code 9A76 */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_9A7E } /* code 9A7E */
  ,{  24,  24,  3, (void GUI_FLASH *)&acFontSongTi18_Warning_FF01 } /* code FF01 */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop30 = {
   0xFF01 /* first character */
  ,0xFF01 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 29] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop29 = {
   0x9A7E /* first character */
  ,0x9A7E /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 28] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop28 = {
   0x9A76 /* first character */
  ,0x9A76 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 27] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop27 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 26] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop26 = {
   0x90E8 /* first character */
  ,0x90E8 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 25] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop25 = {
   0x8F93 /* first character */
  ,0x8F93 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 24] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop24 = {
   0x8F66 /* first character */
  ,0x8F66 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 23] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop23 = {
   0x8BF7 /* first character */
  ,0x8BF7 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 22] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop22 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 21] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop21 = {
   0x8BC1 /* first character */
  ,0x8BC1 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 20] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop20 = {
   0x8B66 /* first character */
  ,0x8B66 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 19] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop19 = {
   0x88AB /* first character */
  ,0x88AB /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 18] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop18 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 17] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop17 = {
   0x724C /* first character */
  ,0x724C /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 16] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop16 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 15] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop15 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 14] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop14 = {
   0x6CD5 /* first character */
  ,0x6CD5 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 13] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop13 = {
   0x6C11 /* first character */
  ,0x6C11 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 12] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop12 = {
   0x6267 /* first character */
  ,0x6267 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 11] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop11 = {
   0x6240 /* first character */
  ,0x6240 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[ 10] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop10 = {
   0x5C5E /* first character */
  ,0x5C5E /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  9] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop9 = {
   0x59D3 /* first character */
  ,0x59D3 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  8] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop8 = {
   0x5730 /* first character */
  ,0x5730 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  7] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop7 = {
   0x540D /* first character */
  ,0x540D /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  6] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop6 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  5] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop5 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  4] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop4 = {
   0x52E4 /* first character */
  ,0x52E4 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  3] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop3 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  2] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop2 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  1] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSongTi18_Warning_Prop1 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_FontSongTi18_Warning_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontSongTi18_Warning = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontSongTi18_Warning_Prop1
};

