/*
  C-file generated by µC/GUI-FontConvert Demo  V2.16b
  Compiled:    Jul 23 2002 at 13:13:49

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  






http://www.ucgui.com
2005/07/24
www.ucgui.com


  Source file: SwitchKey.c
  Font:        __
  Height:      19
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontSwitchKey;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_FLASH const unsigned char acFontSwitchKey_5207[ 57] = 
{ /* code 5207 */
	0X00,0X00,0X00,0X00,0X00,0X00,0X00,0X60,0X00,0X00,0Xf0,0X00,0X01,0X98,0X00,0X03,
	0X0C,0X00,0X06,0X06,0X00,0X0C,0Xf3,0X00,0X19,0X09,0X80,0X31,0X08,0Xc0,0X61,0X08,
	0X60,0X7D,0X0B,0Xe0,0X04,0Xf2,0X00,0X1C,0X03,0X80,0X10,0X00,0X80,0X1F,0Xff,0X80,
	0X1F,0Xff,0X80,0X00,0X00,0X00,0X00,0X00,0X00,
};

GUI_FLASH const GUI_CHARINFO GUI_FontSwitchKey_CharInfo[1] = {
   {  19,  19,  3, (void GUI_FLASH *)&acFontSwitchKey_5207 } /* code 5207 */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontSwitchKey_Prop1 = {
   0x5207 /* first character */
  ,0x5207 /* last character  */
  ,&GUI_FontSwitchKey_CharInfo[  0] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontSwitchKey = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontSwitchKey_Prop1
};

