/*
  C-file generated by µC/GUI-FontConvert Demo  V2.16b
  Compiled:    Jul 23 2002 at 13:13:49

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  






http://www.ucgui.com
2005/07/24
www.ucgui.com


  Source file: Tabs.c
  Font:        ___
  Height:      16
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontTabs;

/* Start of unicode area <Box Drawing> */
GUI_FLASH const unsigned char acFontTabs_2500[ 32] = { /* code 2500 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXXXX,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontTabs_2514[ 32] = { /* code 2514 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,XXXXXXXX,
  ________,________,
  ________,________};

GUI_FLASH const unsigned char acFontTabs_2518[ 32] = { /* code 2518 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,________,
  ________,________,
  ________,________};

GUI_FLASH const GUI_CHARINFO GUI_FontTabs_CharInfo[3] = {
   {  16,  16,  2, (void GUI_FLASH *)&acFontTabs_2500 } /* code 2500 */
  ,{  16,  16,  2, (void GUI_FLASH *)&acFontTabs_2514 } /* code 2514 */
  ,{  16,  16,  2, (void GUI_FLASH *)&acFontTabs_2518 } /* code 2518 */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTabs_Prop3 = {
   0x2518 /* first character */
  ,0x2518 /* last character  */
  ,&GUI_FontTabs_CharInfo[  2] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTabs_Prop2 = {
   0x2514 /* first character */
  ,0x2514 /* last character  */
  ,&GUI_FontTabs_CharInfo[  1] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontTabs_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontTabs_Prop1 = {
   0x2500 /* first character */
  ,0x2500 /* last character  */
  ,&GUI_FontTabs_CharInfo[  0] /* address of first character */
  ,(void GUI_FLASH *)&GUI_FontTabs_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontTabs = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontTabs_Prop1
};


