/*
  C-file generated by µC/GUI-FontConvert Demo  V2.16b
  Compiled:    Jul 23 2002 at 13:13:49

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  






http://www.ucgui.com
2005/07/24
www.ucgui.com


  Source file: Uparrow.c
  Font:        __
  Height:      16
*/

#include "GUI.H"

#ifndef GUI_FLASH
  #define GUI_FLASH
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_FLASH const GUI_FONT GUI_FontUparrow;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_FLASH const unsigned char acFontUparrow_7BAD[ 48] = /* code 7BAD */
{	
	0x00,0x00,0x00,0x00,0x80,0x00,0x01,0x40,0x00,0x02,0x20,0x00,0x04,0x10,0x00,0x08,
	0x08,0x00,0x1F,0x7C,0x00,0x01,0x40,0x00,0x01,0x40,0x00,0x01,0x40,0x00,0x01,0x40,
	0x00,0x01,0x40,0x00,0x01,0x40,0x00,0x01,0x40,0x00,0x01,0xC0,0x00,0x00,0x00,0x00,/*"Î´ÃüÃûÎÄ¼þ",0*/
};

GUI_FLASH const GUI_CHARINFO GUI_FontUparrow_CharInfo[1] = {
   {  17,  17,  3, (void GUI_FLASH *)&acFontUparrow_7BAD } /* code 7BAD */
};

GUI_FLASH const GUI_FONT_PROP GUI_FontUparrow_Prop1 = {
   0x7BAD /* first character */
  ,0x7BAD /* last character  */
  ,&GUI_FontUparrow_CharInfo[  0] /* address of first character */
  ,(void*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_FLASH const GUI_FONT GUI_FontUparrow = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,(void GUI_FLASH *)&GUI_FontUparrow_Prop1
};

